#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}

GUI_PORT=${GUI_PORT:-8384}

umask "$UMASK_SET"

exec \
        s6-setuidgid abc syncthing \
        -home=/config -no-browser -no-restart \
        --gui-address="0.0.0.0:$GUI_PORT"